# Generated by Django 2.2.5 on 2020-03-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20200217_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=225, verbose_name='Açıklama')),
                ('file', models.ImageField(blank=True, null=True, upload_to='media')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='result',
            name='file',
            field=models.ImageField(blank=True, upload_to='result'),
        ),
    ]
